### ISSUE TITLE
지역선택 이슈

### ISSUE THREAD

**Issue by dusvlf111** [inje-megabrain/irBs#7]
지역 밑에 등-하교는 항상 시간표가 같은지 확인 후 만약 다르면 당일 시간표로 띄우게 할건지 의견 필요.

**Comment by dusvlf111** [comment]
11.04 회의에 의논 ㄱㄱ 
당일로 하는게 좋지 않을까 아니면 지우는것도 괜찮을듯
@singhic

**Comment by singhic** [comment]
확인했습니다
